apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "pipefy"
  description: "Pipefy integration with our Core BI, used by Controle Economico de TI - Brasil"
  annotations:
    #bitbucket.org/project-slug: undefined/undefined/undefined
    backstage.io/techdocs-ref: dir:.

spec:
  type: website
  lifecycle: experimental
  owner: "asabreu_mapfre.com.br"